<?php


namespace BigCommerce_Price_Cache\Rest;

use BigCommerce\Rest\Pricing_Controller;

class Cached_Pricing_Controller extends Pricing_Controller {
	public function get_items( $request ) {
		return parent::get_items( $request ); // TODO: Change the autogenerated stub
	}

}
